"""GigaChat text2image provider for the image generation pipeline."""

import asyncio
import base64
import logging
import re
import threading
from typing import Optional, Tuple
from uuid import uuid4

from gigachat import GigaChat
from gigachat.models import Chat, Messages, MessagesRole

from AI.gigachat_client import GIGACHAT_BASE_URL
from core.settings import GIGACHAT_API_KEY


_IMAGE_SRC_RE = re.compile(r'<img[^>]+src="([^"]+)"', re.IGNORECASE)
_SYNC_LOCK = threading.Lock()


gigachat_image_client = GigaChat(
    credentials=GIGACHAT_API_KEY,
    base_url=GIGACHAT_BASE_URL,
    model="GigaChat-2",
    verify_ssl_certs=False,
    timeout=120,
)


def _decode_image_content(content) -> bytes:
    if isinstance(content, bytes):
        if content.startswith((b"\x89PNG", b"\xff\xd8\xff")):
            return content
        return base64.b64decode(content)
    if isinstance(content, str):
        return base64.b64decode(content)
    raise TypeError(f"Unsupported GigaChat image content type: {type(content)!r}")


def _usage_to_log(usage) -> str:
    if usage is None:
        return "usage=unknown"
    prompt_tokens = getattr(usage, "prompt_tokens", None)
    completion_tokens = getattr(usage, "completion_tokens", None)
    total_tokens = getattr(usage, "total_tokens", None)
    return (
        f"prompt_tokens={prompt_tokens} "
        f"completion_tokens={completion_tokens} total_tokens={total_tokens}"
    )


def _generate_gigachat_image_sync(prompt: str) -> Optional[bytes]:
    """Generate one image via the built-in GigaChat text2image function."""
    request_prompt = (
        "Нарисуй изображение по следующему описанию. "
        "Не добавляй на изображение текст, подписи или водяные знаки, если это явно не требуется.\n"
        f"Описание: {prompt.strip()}"
    )

    with _SYNC_LOCK:
        response = gigachat_image_client.chat(
            Chat(
                messages=[
                    Messages(
                        role=MessagesRole.USER,
                        content=request_prompt,
                    )
                ],
                function_call="auto",
            )
        )

        logging.info(
            "GigaChat image response: model=%s %s",
            getattr(response, "model", None),
            _usage_to_log(getattr(response, "usage", None)),
        )

        content = response.choices[0].message.content or ""
        match = _IMAGE_SRC_RE.search(content)
        if not match:
            logging.warning(
                "GigaChat image response did not contain <img src=...>: %s",
                content[:500],
            )
            return None

        file_id = match.group(1)
        image = gigachat_image_client.get_image(file_id)
        image_bytes = _decode_image_content(image.content)
        logging.info(
            "GigaChat image downloaded: file_id=%s size=%s bytes",
            file_id,
            len(image_bytes),
        )
        return image_bytes


async def generate_gigachat_image(prompt: str) -> Optional[bytes]:
    try:
        return await asyncio.to_thread(_generate_gigachat_image_sync, prompt)
    except Exception as exc:
        logging.warning("GigaChat image generation failed: %s", exc)
        return None


class GigaChatImageCompatAPI:
    """Adapter for the old Kandinsky-shaped fallback used by `скаламбурь`.

    `AI.picgeneration.handle_pun_image_command` historically expects a provider
    with get_pipeline/generate/check methods. The adapter keeps that path stable
    while the actual image is generated by GigaChat-2 text2image.
    """

    def __init__(self):
        self._pending: dict[str, bytes] = {}
        self._pending_lock = threading.Lock()

    def get_pipeline(self) -> str:
        return "GigaChat-2"

    def generate(self, prompt: str, pipeline_id: str) -> Tuple[Optional[str], Optional[str]]:
        try:
            image_bytes = _generate_gigachat_image_sync(prompt)
            if not image_bytes:
                return None, "GigaChat returned no image"
            request_id = str(uuid4())
            with self._pending_lock:
                self._pending[request_id] = image_bytes
            return request_id, None
        except Exception as exc:
            logging.warning("GigaChat compat generate failed: %s", exc)
            return None, str(exc)

    def check(self, request_id: str) -> Tuple[Optional[bytes], Optional[str]]:
        with self._pending_lock:
            image_bytes = self._pending.pop(request_id, None)
        if image_bytes is None:
            return None, "GigaChat image result not found"
        return image_bytes, None


def install_into_picgeneration(picgeneration_module) -> None:
    """Replace the Kandinsky stage with GigaChat without refactoring the whole module."""

    # The legacy pun handler reads these globals dynamically. Pointing them at
    # this adapter transparently switches its Kandinsky fallback to GigaChat.
    picgeneration_module.kandinsky_api = GigaChatImageCompatAPI()
    picgeneration_module.PIPELINE_ID = None

    async def robust_image_generation(message, prompt_ru, processing_msg, skip_translate=False):
        # 1. GigaChat-2 text2image. It understands Russian directly, so do not
        # spend time/tokens translating the prompt until the first provider fails.
        await processing_msg.edit_text("Использую ебучий GigaChat...")
        img = await generate_gigachat_image(prompt_ru)
        if img:
            await processing_msg.delete()
            return await picgeneration_module.send_generated_photo(message, img, "gigachat.png")

        # Translate/enhance only for providers that benefit from an English prompt.
        prompt_en = prompt_ru if skip_translate else await picgeneration_module.translate_to_en(prompt_ru)

        # 2. Pollinations / Flux
        await processing_msg.edit_text("Использую ебучий Flux...")
        img = await picgeneration_module.pollinations_generate(prompt_en)
        if img:
            await processing_msg.delete()
            return await picgeneration_module.send_generated_photo(message, img, "flux.png")

        # 3. Existing reserves
        await processing_msg.edit_text("Использую резервный анал...")
        img = await picgeneration_module.hf_generate(
            prompt_en,
            "black-forest-labs/FLUX.1-schnell",
        )
        if not img:
            img = await picgeneration_module.cf_generate_t2i(prompt_en)

        if img:
            await processing_msg.delete()
            return await picgeneration_module.send_generated_photo(message, img, "ai_image.png")

        await processing_msg.edit_text("Иди нахуй, я спать")
        return None

    async def handle_gigachat_generation_command(message):
        source_text = message.text or message.caption or ""
        prompt = re.sub(r"^\s*сгенерируй\b", "", source_text, flags=re.IGNORECASE).strip()
        if not prompt and message.reply_to_message:
            prompt = message.reply_to_message.text or message.reply_to_message.caption or ""
        if not prompt:
            return await message.reply("Что сгенерировать?")

        msg = await message.reply("Ща падажжи ебана.")
        return await robust_image_generation(message, prompt, msg)

    picgeneration_module.robust_image_generation = robust_image_generation
    # Keep the historical exported function name so handlers/imports stay compatible.
    picgeneration_module.handle_kandinsky_generation_command = handle_gigachat_generation_command
