name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main # Запускать етот workflow при каждом push в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest # Используем свежую Ubuntu для выполнения workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Скачиваем ваш код из репозитория

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} # Используем приватный SSH-ключ из секретов GitHub

      - name: Deploy to Server
        run: |
          echo "Deploying to production server..."
          # Убедитесь, что ваш публичный ключ добавлен на сервер (в ~/.ssh/authorized_keys)
          # и что у пользователя root есть доступ по SSH с этим ключом
          # или используйте другого пользователя, если root по SSH отключен
          
          ssh -o StrictHostKeyChecking=no root@31.56.240.156 "cd /root/upupa/ && \
            # --- Добавляем эту команду, чтобы настроить origin на SSH URL ---
            git remote set-url origin git@github.com:lingvofil/upupa.git && \
            # Теперь git pull будет использовать SSH-ключ для аутентификации с GitHub
            git pull origin main && \
            sudo systemctl restart upupa_bot.service"
          echo "Deployment complete."